# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and deploy

name: deployment to github page

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Deploy to GitHub Pages
          # You may pin to the exact commit or the version.
          # uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        # This is the branch you wish to deploy to, for example gh-pages or docs.
        branch: gh-pages
        # The folder in your repository that you want to deploy. If your build script compiles into a directory named build you would put it here. Folder paths cannot have a leading / or ./. If you wish to deploy the root directory you can place a . here.
        folder: public
 


